apiVersion: apps/v1
kind: Deployment
metadata:
  name: md5-hash-server
  labels:
    app.kubernetes.io/instance: md5-hash-server
    app.kubernetes.io/name: md5-hash-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: md5-hash-server
      app.kubernetes.io/name: md5-hash-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: md5-hash-server
        app.kubernetes.io/name: md5-hash-server
    spec:
      containers:
        - name: md5-hash-server
          image: 'Build 完的image name'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: cache-volume
              mountPath: /tmp
      volumes:
      - name: cache-volume
        emptyDir: {}
      restartPolicy: Always
